name: flutter_wallet_connect
description: "Flutter Web3 Wallet for Tokens and NFTs."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  moralis: ^0.0.3+4
  http: ^0.13.6
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.1
  video_player: ^2.9.2
  bip39: ^1.0.6
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
  loading_animation_widget: ^1.3.0
  logger: ^1.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/intro.mp4
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
